### ISSUE TITLE
site-header gets background color on tablet and mobile

### ISSUE THREAD

**Issue by kat05** [getgrav/grav-skeleton-receptar-site#1]
Please see pic, the top of the image should probably display there instead of the background color.
![receptar](https://cloud.githubusercontent.com/assets/5719486/12510033/2910da78-c107-11e5-8d97-16f06b9b2a7b.png)

**Comment by hexplor** [comment]
Hmmm. I don't think so. Original theme (Wordpress) also work this way so I guess it was author's original intention :)
