### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by ocean123** [getgrav/grav-skeleton-receptar-site#2]
Hi,

can you add this in base.html.twig for the next update

{% do assets.addCss('theme://css/custom.css',-100) %}

**Comment by flaviocopes** [comment]
Hi, this is the _skeleton_ repository. It just uses the Receptar theme, plus some plugins, and provides pages and config.

Please open this [on the theme repo](https://github.com/getgrav/grav-theme-receptar), or better yet, edit the file yourself and submit a PR.
